version: "3.7"

services:

  samba:
    image: dperson/samba # no tag with versions, only latest
    restart: always
    command: '-u "pi;password" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no"'
    stdin_open: true
    tty: true
    environment:
      - TZ=America/Mexico_City
    ports:
      - 139:139
      - 445:445
    volumes:
      - ${MEDIA}:/media
      - ${STORAGE}/torrents:/downloads

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    expose:
      - 32400
      - 33400
    # # Uncomment if you are NOT using network_mode: "host"
    # ports:
    #  - 32400:32400
    #  - 33400:33400
    environment:
      - PUID=1000  # Ajusta esto a tu usuario
      - PGID=1000  # Ajusta esto a tu grupo
      - TZ=America/Mexico_City
    volumes:
      - ${STORAGE}/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${TV_PATH}:/tv
      - ${MOVIES_PATH}:/movies
    restart: unless-stopped
    network_mode: "host" # Only works on Linux

  transmission:
    image : jaymoulin/transmission:3.00-1.6.1
    command: transmission-daemon -f -g /config
    volumes:
      - ./transmission:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Mexico_City
    volumes:
      - ${STORAGE}/sonarr/config:/config
      - ${MEDIA}/tv:/tv
      - ${STORAGE}/torrents:/downloads

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Mexico_City
    volumes:
      - ${STORAGE}/radarr/config:/config
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}/movies:/movies

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    ports:
      - "9117:9117"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Mexico_City
    volumes:
      - ${STORAGE}/jackett/config:/config
      - ${STORAGE}/jackett/downloads:/downloads

networks:
  plexnet:
    driver: bridge